name: maven release demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install maven
        run: sudo apt install maven

      - name: Configure git user
        run: |
          git config user.email "githubactions@planetpayment.com"
          git config user.name "GHA '${{ github.workflow }}' workflow, on behalf of ${{ github.actor }}."

      - name: Release
        run: |
          mvn clean release:prepare -DpushChanges=false
          git push origin
